CUDA_VISIBLE_DEVICES=4 python train.py \
--dataroot /local/scratch/datasets/FullbodySCT/Synthrad_combined_preprocessed/7materialized_splits_31baselineBodyRegion/AB/cyclegan/train \
--checkpoints_dir /local/scratch/datasets/FullbodySCT/Synthrad_combined_preprocessed/8checkpoints \
--name cut_synthrad_abdomen_sep_first_layer \
--model cut \
--CUT_mode CUT \
--output_nc 1 \
--input_nc 1 \
--batch_size 1 \
--netG resnet_9blocks_sep_first_layer \
--n_epochs 100 \
--n_epochs_decay 0 \
--no_html \
--preprocess None \
--print_freq 1000 \
--save_epoch_freq 1